#!/usr/bin/env Rscript
############################################################
## Quantile PRS figures for the manuscript.
##
## Inputs are quantile_or_Q5 tables generated by:
##   02_lrs_prs_pc20.R
##   02_ngs_prs_deepvar_pc20_batch.R
##
## Outputs:
##   1) SCZ-only main-text quantile figure
##   2) BIP/ADHD/MDD/ASD supplementary quantile OR figure
############################################################

cmd_args <- commandArgs(FALSE)
file_arg <- sub("^--file=", "", cmd_args[grep("^--file=", cmd_args)])
script_dir <- if (length(file_arg)) dirname(normalizePath(file_arg[1])) else getwd()
source(file.path(script_dir, "prs_common.R"))

base_dir <- Sys.getenv("RESULT_ROOT", file.path(dirname(script_dir), "results", "prs"))
n_pcs <- as.integer(Sys.getenv("N_PCS", "20"))
n_quantile <- as.integer(Sys.getenv("N_QUANTILE", "5"))

lrs_mark <- paste0("lrs_pc", n_pcs)
ngs_mark <- paste0("ngs_deepvar_pc", n_pcs, "_batch")
lrs_table_dir <- file.path(base_dir, "figure", lrs_mark, "tables")
ngs_table_dir <- file.path(base_dir, "figure", ngs_mark, "tables")
outdir <- file.path(base_dir, "figure", paste0("quantile_main_supp_pc", n_pcs))
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

trait_order <- c("SCZ", "BIP", "ADHD", "MDD", "ASD")
supp_traits <- c("BIP", "ADHD", "MDD", "ASD")

required_cols <- c(
  "Trait", "Quantile", "Quantile_num", "OR", "CI_low", "CI_high", "P",
  "n", "n_case", "n_HC", "case_fraction"
)

read_quantile_table <- function(table_dir, mark, dataset_label) {
  file <- file.path(table_dir, paste0("quantile_or_Q", n_quantile, "_", mark, ".tsv"))
  if (!file.exists(file)) stop("Missing quantile table: ", file)
  dt <- fread(file)
  missing_cols <- setdiff(required_cols, names(dt))
  if (length(missing_cols)) {
    stop("Quantile table lacks required column(s): ", paste(missing_cols, collapse = ", "), " in ", file)
  }
  dt[, dataset := dataset_label]
  dt[, Trait := factor(as.character(Trait), levels = trait_order)]
  dt[, Quantile := factor(as.character(Quantile), levels = paste0("Q", seq_len(n_quantile)))]
  dt[, Quantile_num := as.integer(Quantile_num)]
  list(data = dt, file = file)
}

format_p <- function(p) {
  ifelse(
    is.na(p),
    "P = NA",
    ifelse(p < 1e-4, paste0("P = ", formatC(p, format = "e", digits = 2)), paste0("P = ", signif(p, 3)))
  )
}

format_or_label <- function(dt) {
  top_q <- paste0("Q", n_quantile)
  z <- dt[as.character(Quantile) == top_q]
  if (!nrow(z)) return("")
  paste0(
    top_q, " vs Q1\n",
    "OR = ", sprintf("%.2f", z$OR[1]), "\n",
    format_p(z$P[1])
  )
}

make_or_panel <- function(dt, trait, dataset_label, annotate_top = FALSE, show_x = TRUE, show_y = TRUE) {
  dd <- dt[as.character(Trait) == trait & dataset == dataset_label]
  if (!nrow(dd)) stop("No quantile data for ", dataset_label, " ", trait)
  ymax <- max(dd$CI_high, dd$OR, na.rm = TRUE)
  ymin <- min(dd$CI_low, dd$OR, na.rm = TRUE)
  if (!is.finite(ymax) || ymax <= 0) ymax <- 2
  if (!is.finite(ymin) || ymin <= 0) ymin <- 0.5
  ann <- data.frame(
    x = n_quantile - 0.15,
    y = ymax * 0.92,
    label = format_or_label(dd)
  )

  p <- ggplot(dd, aes(x = Quantile_num, y = OR)) +
    geom_hline(yintercept = 1, linetype = "dashed", linewidth = 0.32, color = "grey45") +
    geom_errorbar(aes(ymin = CI_low, ymax = CI_high), width = 0.12, linewidth = 0.48, color = trait_cols[[trait]]) +
    geom_point(size = 2.1, color = trait_cols[[trait]]) +
    scale_x_continuous(breaks = seq_len(n_quantile), labels = paste0("Q", seq_len(n_quantile))) +
    scale_y_log10() +
    coord_cartesian(ylim = c(ymin * 0.85, ymax * 1.18), clip = "off") +
    labs(
      title = paste(dataset_label, trait),
      x = if (show_x) "PRS residual quantile" else NULL,
      y = if (show_y) "Odds ratio vs Q1" else NULL
    ) +
    theme_prs(9) +
    theme(
      legend.position = "none",
      plot.title = element_text(face = "bold", size = 9),
      axis.text.x = element_text(size = 8)
    )

  if (isTRUE(annotate_top)) {
    p <- p + geom_text(
      data = ann,
      aes(x = x, y = y, label = label),
      inherit.aes = FALSE,
      hjust = 1,
      vjust = 1,
      size = 2.45,
      lineheight = 0.95
    )
  }
  p
}

make_case_panel <- function(dt, trait, dataset_label, show_x = TRUE, show_y = TRUE) {
  dd <- dt[as.character(Trait) == trait & dataset == dataset_label]
  if (!nrow(dd)) stop("No quantile data for ", dataset_label, " ", trait)
  ymax <- max(dd$case_fraction, na.rm = TRUE)
  if (!is.finite(ymax) || ymax <= 0) ymax <- 0.1
  dd[, count_label := paste0(n_case, "/", n)]

  ggplot(dd, aes(x = Quantile, y = case_fraction)) +
    geom_col(width = 0.68, fill = trait_cols[[trait]], color = "grey30", linewidth = 0.15) +
    geom_text(aes(label = count_label), vjust = -0.35, size = 2.35) +
    scale_y_continuous(
      limits = c(0, min(1, ymax * 1.24)),
      labels = function(x) paste0(round(100 * x), "%"),
      expand = expansion(mult = c(0, 0.02))
    ) +
    labs(
      title = paste(dataset_label, trait),
      x = if (show_x) "PRS residual quantile" else NULL,
      y = if (show_y) "Case proportion" else NULL
    ) +
    theme_prs(9) +
    theme(
      legend.position = "none",
      plot.title = element_text(face = "bold", size = 9),
      axis.text.x = element_text(size = 8)
    )
}

lrs <- read_quantile_table(lrs_table_dir, lrs_mark, "LRS")
ngs <- read_quantile_table(ngs_table_dir, ngs_mark, "short-read WGS")
quantile_dt <- rbindlist(list(lrs$data, ngs$data), use.names = TRUE, fill = TRUE)
quantile_dt[, dataset := factor(dataset, levels = c("LRS", "short-read WGS"))]

scz_main <- plot_grid(
  make_or_panel(quantile_dt, "SCZ", "LRS", annotate_top = TRUE, show_x = FALSE, show_y = TRUE),
  make_or_panel(quantile_dt, "SCZ", "short-read WGS", annotate_top = TRUE, show_x = FALSE, show_y = TRUE),
  make_case_panel(quantile_dt, "SCZ", "LRS", show_x = TRUE, show_y = TRUE),
  make_case_panel(quantile_dt, "SCZ", "short-read WGS", show_x = TRUE, show_y = TRUE),
  ncol = 2,
  labels = LETTERS[1:4],
  label_size = 10,
  align = "hv",
  axis = "tblr"
)

scz_prefix <- file.path(outdir, paste0("main_SCZ_quantile_OR_case_fraction_Q", n_quantile, "_lrs_ngs_pc", n_pcs))
save_plot_pair(scz_main, scz_prefix, 18, 16)

supp_panels <- c(
  lapply(supp_traits, function(trait) make_or_panel(quantile_dt, trait, "LRS", show_x = FALSE, show_y = trait == supp_traits[1])),
  lapply(supp_traits, function(trait) make_or_panel(quantile_dt, trait, "short-read WGS", show_x = TRUE, show_y = trait == supp_traits[1]))
)

supp_fig <- plot_grid(
  plotlist = supp_panels,
  ncol = length(supp_traits),
  labels = LETTERS[seq_along(supp_panels)],
  label_size = 9,
  align = "hv",
  axis = "tblr"
)

supp_prefix <- file.path(outdir, paste0("supplement_nonSCZ_quantile_OR_Q", n_quantile, "_lrs_ngs_pc", n_pcs))
save_plot_pair(supp_fig, supp_prefix, 30, 13)

top_q_summary <- quantile_dt[Quantile_num == n_quantile, .(
  dataset,
  Trait = as.character(Trait),
  Quantile = as.character(Quantile),
  OR,
  CI_low,
  CI_high,
  P,
  n,
  n_case,
  n_HC,
  case_fraction
)]
top_q_summary[, trait_rank := match(Trait, trait_order)]
setorder(top_q_summary, dataset, trait_rank)
top_q_summary[, trait_rank := NULL]
fwrite(
  top_q_summary,
  file.path(outdir, paste0("top_quantile_vs_Q1_summary_Q", n_quantile, "_lrs_ngs_pc", n_pcs, ".tsv")),
  sep = "\t",
  quote = FALSE
)

manifest <- data.table(
  dataset = c("LRS", "short-read WGS"),
  file_type = "quantile_or_case_fraction",
  file = c(lrs$file, ngs$file)
)
fwrite(
  manifest,
  file.path(outdir, paste0("quantile_main_supp_input_manifest_pc", n_pcs, ".tsv")),
  sep = "\t",
  quote = FALSE
)

message("[DONE] SCZ main quantile figure: ", paste0(scz_prefix, ".pdf"))
message("[DONE] Supplementary non-SCZ quantile figure: ", paste0(supp_prefix, ".pdf"))
